import { response, route } from '@stacksjs/router'

/**
 * This file is the entry point for your application's API routes.
 * The routes defined here are automatically registered. Last but
 * not least, you may also create any other `routes/*.ts` files.
 *
 * Framework routes (auth, dashboard, commerce, CMS, etc.) are loaded
 * automatically from storage/framework/defaults/routes/dashboard.ts.
 * You do NOT need to define them here — only add your own custom routes.
 *
 * @see https://docs.stacksjs.com/routing
 */

// Your custom routes go here:
route.get('/', () => response.text('hello world'))

// Monitor CRUD (index/store/show/update/destroy) is auto-generated by the
// `useApi` trait on app/Models/Monitor.ts. This is the one custom action —
// triggering an out-of-band check outside the scheduler's normal cadence.
route.post('/monitors/{id}/check', 'Actions/Monitors/RunCheckAction')

// Public heartbeat ping endpoint (no auth — the token itself is the secret).
// GET *and* POST both work since cron jobs commonly just `curl` the URL.
route.get('/ping/{token}', 'Actions/Heartbeats/ReceivePingAction')
route.post('/ping/{token}', 'Actions/Heartbeats/ReceivePingAction')

// `/coming-soon` is served as an STX view from
// `storage/framework/defaults/resources/views/coming-soon.stx`. The
// view auto-resolves through stx-serve, so no route registration is
// needed here. To activate the holding page across the whole app:
//
//   ./buddy coming-soon [--secret=my-magic-token]
//
// Launch the site with `./buddy launch`. Maintenance mode (503 page,
// distinct cookie + state file) is the separate `./buddy down` /
// `./buddy up` pair.
