import { route } from '@stacksjs/router'

/**
 * This file is the entry point for your application's API routes.
 * The routes defined here are automatically registered. Last but
 * not least, you may also create any other `routes/*.ts` files.
 *
 * Framework routes (auth, dashboard, commerce, CMS, etc.) are loaded
 * automatically from storage/framework/defaults/routes/dashboard.ts.
 * You do NOT need to define them here — only add your own custom routes.
 *
 * @see https://docs.stacksjs.com/routing
 */

// No route.get('/', ...) here: static views win over programmatic routes
// at the same path in this router, so resources/views/index.stx always
// handles '/' regardless of what's registered here. Custom status page
// domains (stacksjs/status#1 Phase 7) are resolved inside that view's
// own <script server> block instead — see the comment at the top of
// resources/views/index.stx for why.

// Monitor CRUD (index/show/update/destroy) is auto-generated by the
// `useApi` trait on app/Models/Monitor.ts. `store` is overridden here
// (user-defined routes take priority over the auto-generated ones) to
// enforce the team's plan limit before creating — see
// Actions/Monitors/CreateMonitorAction. Custom action: triggering an
// out-of-band check outside the scheduler's normal cadence.
route.post('/monitors', 'Actions/Monitors/CreateMonitorAction')
route.post('/monitors/{id}/check', 'Actions/Monitors/RunCheckAction')

// Incident CRUD (index/store/show/update) is auto-generated by the
// `useApi` trait on app/Models/Incident.ts. Custom action: a one-step
// acknowledge, since the auto-generated `update` route requires PATCHing
// the full resource with a status string.
route.post('/incidents/{id}/acknowledge', 'Actions/Incidents/AcknowledgeIncidentAction')

// TeamMember index/show/destroy is auto-generated by the `useApi` trait on
// app/Models/TeamMember.ts. Custom actions: creating a member is always an
// invite (pending until accepted), and acceptance links a real user id.
route.post('/teams/{id}/invite', 'Actions/Teams/InviteTeamMemberAction')
route.post('/team-invites/{uuid}/accept', 'Actions/Teams/AcceptTeamInviteAction')

// Public heartbeat ping endpoint (no auth — the token itself is the secret).
// GET *and* POST both work since cron jobs commonly just `curl` the URL.
route.get('/ping/{token}', 'Actions/Heartbeats/ReceivePingAction')
route.post('/ping/{token}', 'Actions/Heartbeats/ReceivePingAction')

// StatusPage CRUD (index/show/update/destroy) is auto-generated by the
// `useApi` trait on app/Models/StatusPage.ts. `store` is overridden here,
// same pattern as CreateMonitorAction, to enforce the team's plan limit.
route.post('/status-pages', 'Actions/StatusPages/CreateStatusPageAction')

// One-time migration from an existing Better Stack/Instatus/Statuspage.io
// page (stacksjs/status#1 Phase 12).
route.post('/status-pages/import', 'Actions/StatusPages/ImportStatusPageAction')

// Password/email-domain gate for access-controlled status pages
// (stacksjs/status#1 Phase 12) — public, no auth (this route IS the auth).
route.post('/status/{slug}/unlock', 'Actions/StatusPages/UnlockStatusPageAction')

// Status page subscriber signup/unsubscribe — public, no auth.
route.post('/status/{slug}/subscribe', 'Actions/StatusPages/SubscribeAction')
route.get('/status/{slug}/unsubscribe/{token}', 'Actions/StatusPages/UnsubscribeAction')
route.get('/status/{slug}/feed', 'Actions/StatusPages/IncidentFeedAction')

// Dashboard status-page builder form posts (stacksjs/status#1 Phase 8) —
// plain POST + redirect, not the JSON-returning API actions above, since
// these back native HTML <form> elements with no client JS (see
// Actions/StatusPages/UpdateStatusPageAction for why). Deliberately NOT
// under /dashboard/status-pages/* — that collides with the dynamic file
// route resources/views/dashboard/status-pages/[id].stx (e.g. a POST to
// .../create matches [id]="create" as a GET-only view route first and
// 405s) — same "static/dynamic views win over routes at the same path"
// behavior documented at the top of this file, just for a dynamic [id]
// route instead of a static one this time.
route.post('/status-page-forms/create', 'Actions/StatusPages/DashboardCreateStatusPageAction')
route.post('/status-page-forms/{id}/update', 'Actions/StatusPages/UpdateStatusPageAction')
route.post('/status-page-forms/{id}/monitors/add', 'Actions/StatusPages/DashboardAssignMonitorAction')
route.post('/status-page-forms/{id}/monitors/remove', 'Actions/StatusPages/DashboardRemoveMonitorAction')

// Dashboard notification-channel form posts (stacksjs/status#1 Phase 8) —
// same plain-POST convention, and same /*-forms/ naming to dodge the
// dynamic-view-collision explained above (there's no [id].stx under
// dashboard/settings, but keeping the convention consistent avoids
// having to remember which pages need the workaround).
route.post('/notification-channel-forms/create', 'Actions/Notifications/DashboardCreateChannelAction')
route.post('/notification-channel-forms/{id}/test-send', 'Actions/Notifications/DashboardTestSendAction')
route.post('/notification-channel-forms/monitors/{monitorId}/assign', 'Actions/Notifications/DashboardAssignChannelAction')
route.post('/notification-channel-forms/monitors/{monitorId}/remove', 'Actions/Notifications/DashboardRemoveChannelAction')

// Dashboard team settings form posts (stacksjs/status#1 Phase 8) — same
// plain-POST convention.
route.post('/team-forms/{id}/invite', 'Actions/Teams/DashboardInviteTeamMemberAction')
route.post('/team-forms/{id}/remove', 'Actions/Teams/DashboardRemoveTeamMemberAction')

// Billing (stacksjs/status#1 Phase 9). /checkout is a dashboard form
// post, same convention as the rest of this block. /webhook is called
// by Stripe itself — no CSRF token to satisfy (skipCsrf, matching the
// storefront/contact-form precedent above), and its own signature
// verification (StripeWebhookAction) is the real security control.
route.post('/billing-forms/checkout', 'Actions/Billing/CreateCheckoutSessionAction')
route.post('/billing-forms/cancel', 'Actions/Billing/CancelSubscriptionAction')
route.post('/billing-forms/webhook', 'Actions/Billing/StripeWebhookAction').name('billing.webhook').skipCsrf()

// `/coming-soon` is served as an STX view from
// `storage/framework/defaults/resources/views/coming-soon.stx`. The
// view auto-resolves through stx-serve, so no route registration is
// needed here. To activate the holding page across the whole app:
//
//   ./buddy coming-soon [--secret=my-magic-token]
//
// Launch the site with `./buddy launch`. Maintenance mode (503 page,
// distinct cookie + state file) is the separate `./buddy down` /
// `./buddy up` pair.
