import { route } from '@stacksjs/router'

/**
 * This file is the entry point for your application's API routes.
 * The routes defined here are automatically registered. Last but
 * not least, you may also create any other `routes/*.ts` files.
 *
 * Framework routes (auth, dashboard, commerce, CMS, etc.) are loaded
 * automatically from storage/framework/defaults/routes/dashboard.ts.
 * You do NOT need to define them here — only add your own custom routes.
 *
 * @see https://docs.stacksjs.com/routing
 */

// No route.get('/', ...) here: static views win over programmatic routes
// at the same path in this router, so resources/views/index.stx always
// handles '/' regardless of what's registered here. Custom status page
// domains (stacksjs/status#1 Phase 7) are resolved inside that view's
// own <script server> block instead — see the comment at the top of
// resources/views/index.stx for why.

// Monitor CRUD (index/show/update/destroy) is auto-generated by the
// `useApi` trait on app/Models/Monitor.ts. `store` is overridden here
// (user-defined routes take priority over the auto-generated ones) to
// enforce the team's plan limit before creating — see
// Actions/Monitors/CreateMonitorAction. Custom action: triggering an
// out-of-band check outside the scheduler's normal cadence.
route.post('/monitors', 'Actions/Monitors/CreateMonitorAction')
route.post('/monitors/{id}/check', 'Actions/Monitors/RunCheckAction')

// Incident CRUD (index/store/show/update) is auto-generated by the
// `useApi` trait on app/Models/Incident.ts. Custom action: a one-step
// acknowledge, since the auto-generated `update` route requires PATCHing
// the full resource with a status string.
route.post('/incidents/{id}/acknowledge', 'Actions/Incidents/AcknowledgeIncidentAction')

// TeamMember index/show/destroy is auto-generated by the `useApi` trait on
// app/Models/TeamMember.ts. Custom actions: creating a member is always an
// invite (pending until accepted), and acceptance links a real user id.
route.post('/teams/{id}/invite', 'Actions/Teams/InviteTeamMemberAction')
route.post('/team-invites/{uuid}/accept', 'Actions/Teams/AcceptTeamInviteAction')

// Public heartbeat ping endpoint (no auth — the token itself is the secret).
// GET *and* POST both work since cron jobs commonly just `curl` the URL.
route.get('/ping/{token}', 'Actions/Heartbeats/ReceivePingAction')
route.post('/ping/{token}', 'Actions/Heartbeats/ReceivePingAction')

// StatusPage CRUD (index/show/update/destroy) is auto-generated by the
// `useApi` trait on app/Models/StatusPage.ts. `store` is overridden here,
// same pattern as CreateMonitorAction, to enforce the team's plan limit.
route.post('/status-pages', 'Actions/StatusPages/CreateStatusPageAction')

// Password/email-domain gate for access-controlled status pages
// (stacksjs/status#1 Phase 12) — public, no auth (this route IS the auth).
route.post('/status/{slug}/unlock', 'Actions/StatusPages/UnlockStatusPageAction')

// Status page subscriber signup/unsubscribe — public, no auth.
route.post('/status/{slug}/subscribe', 'Actions/StatusPages/SubscribeAction')
route.get('/status/{slug}/unsubscribe/{token}', 'Actions/StatusPages/UnsubscribeAction')
route.get('/status/{slug}/feed', 'Actions/StatusPages/IncidentFeedAction')

// `/coming-soon` is served as an STX view from
// `storage/framework/defaults/resources/views/coming-soon.stx`. The
// view auto-resolves through stx-serve, so no route registration is
// needed here. To activate the holding page across the whole app:
//
//   ./buddy coming-soon [--secret=my-magic-token]
//
// Launch the site with `./buddy launch`. Maintenance mode (503 page,
// distinct cookie + state file) is the separate `./buddy down` /
// `./buddy up` pair.
